### ISSUE TITLE
if bot.SetUpdateHandler(functionName) is not called you get a panic on any update.

### ISSUE THREAD

**Issue by ghost** [KaikyuDev/GoBot#1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5f0876]

goroutine 1 [running]:
github.com/kaikyudev/gobot.(*Bot).elaborateUpdate(0xc0420f0000, 0x39cce36e, 0x13e4f, 0x1fa076fc, 0x0, 0xc04204c6d0, 0x8, 0x0, 0x0, 0xc04204c6d8, ...)
  C:/Users/M*******/go/src/github.com/kaikyudev/gobot/Bot.go:63 +0x1d6
github.com/kaikyudev/gobot.(*Bot).pollingFunction(0xc0420f0000)
  C:/Users/M*******/go/src/github.com/kaikyudev/gobot/Bot.go:74 +0xe9
github.com/kaikyudev/gobot.(*Bot).StartPolling(0xc0420f0000, 0xc04215cc01)
  C:/Users/M*******/go/src/github.com/kaikyudev/gobot/Bot.go:82 +0x32
main.main()
  C:/Users/M*******/go/src/HakaseBot/Hakase.go:15 +0x112

Process finished with exit code 2

**Comment by KaikyuLotus** [comment]
I'm going to fix it on the next update, thanks for reporting!
